import { readFile, writeFile } from "node:fs/promises";

const stateUrl = new URL("../project/project-state.json", import.meta.url);
const statusUrl = new URL("../project/STATUS.md", import.meta.url);
const state = JSON.parse(await readFile(stateUrl, "utf8"));

const label = (value) =>
  value === null || value === undefined
    ? "Not recorded"
    : String(value)
        .replaceAll("-", " ")
        .replace(/\b\w/g, (character) => character.toUpperCase());
const yesNo = (value) => (value ? "Yes" : "No");
const approval = (value) => (value === null ? "Not recorded" : value ? "Approved" : "Not approved");
const list = (items) => (items.length ? items.map((item) => `- ${item}`).join("\n") : "None.");

const checkpoint = state.lastCheckpoint
  ? `- ID: \`${state.lastCheckpoint.id}\`\n- Completed at: ${state.lastCheckpoint.completedAt}`
  : "None recorded.";

const output = `# Project status

> Generated from \`project/project-state.json\`. Do not edit this file directly.

## Current workflow

- Phase: ${label(state.workflow.phase)}
- Status: ${label(state.workflow.status)}
- Course checkpoint: \`${state.workflow.courseCheckpointId}\`
- Next action: ${state.workflow.nextAction}
- Repository: ${state.project.repository ?? "Not recorded"}

## Approvals

- Scope: ${approval(state.approvals.scope)}
- Website plan: ${approval(state.approvals.websitePlan)}
- Design: ${approval(state.approvals.design)}
- Final website: ${approval(state.approvals.finalWebsite)}

## Design

- Status: ${label(state.design.status)}
- Concepts: ${state.design.conceptCount ?? "Not recorded"}
- Selected concept: ${state.design.selectedConcept ?? "Not recorded"}

## Implementation

- Status: ${label(state.implementation.status)}
- Site mode: ${label(state.implementation.siteMode)}
- Noindex: ${yesNo(state.implementation.noindex)}

## Deployment

- Provider: ${label(state.deployment.provider)}
- Method: ${label(state.deployment.deploymentMethod)}
- Promotion: ${label(state.deployment.promotionMode)}
- Repository visibility: ${label(state.deployment.repositoryVisibility)}
- Worker: ${state.deployment.workerName ?? "Not recorded"}
- Workers.dev URL: ${state.deployment.workersDevUrl ?? "Not recorded"}
- Production URL: ${state.deployment.productionUrl ?? "Not recorded"}
- Custom domain decision: ${label(state.deployment.customDomainDecision)}
- Custom domain: ${state.deployment.customDomain ?? "Not recorded"}
- Last verified commit: ${state.deployment.deployedCommit ?? "Not recorded"}
- Verified at: ${state.deployment.verifiedAt ?? "Not recorded"}
- Fallback reason: ${state.deployment.fallbackReason ?? "Not recorded"}

## Last checkpoint

${checkpoint}

## Blockers

${list(state.blockers)}

## Conflicts

${list(state.conflicts)}
`;

if (process.argv.includes("--check")) {
  const current = await readFile(statusUrl, "utf8").catch(() => "");
  if (current !== output) {
    console.error("project/STATUS.md is out of sync. Run npm run sync:status.");
    process.exit(1);
  }
  console.log("Project status is synchronized.");
} else {
  await writeFile(statusUrl, output, "utf8");
  console.log("Updated project/STATUS.md.");
}
